package com.jw.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_class
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Class {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.class_id
     *
     * @mbggenerated
     */
    private Long classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.subject_name
     *
     * @mbggenerated
     */
    private String subjectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.last_modify_time
     *
     * @mbggenerated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.class_id
     *
     * @return the value of tb_class.class_id
     *
     * @mbggenerated
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.class_id
     *
     * @param classId the value for tb_class.class_id
     *
     * @mbggenerated
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.subject_name
     *
     * @return the value of tb_class.subject_name
     *
     * @mbggenerated
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.subject_name
     *
     * @param subjectName the value for tb_class.subject_name
     *
     * @mbggenerated
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.create_time
     *
     * @return the value of tb_class.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.create_time
     *
     * @param createTime the value for tb_class.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.last_modify_time
     *
     * @return the value of tb_class.last_modify_time
     *
     * @mbggenerated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.last_modify_time
     *
     * @param lastModifyTime the value for tb_class.last_modify_time
     *
     * @mbggenerated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.remark
     *
     * @return the value of tb_class.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.remark
     *
     * @param remark the value for tb_class.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}