package com.jw.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_subject
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Subject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_subject.subject_id
     *
     * @mbggenerated
     */
    private Long subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_subject.subject_name
     *
     * @mbggenerated
     */
    private String subjectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_subject.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_subject.last_modify_time
     *
     * @mbggenerated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_subject.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_subject.subject_id
     *
     * @return the value of tb_subject.subject_id
     *
     * @mbggenerated
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_subject.subject_id
     *
     * @param subjectId the value for tb_subject.subject_id
     *
     * @mbggenerated
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_subject.subject_name
     *
     * @return the value of tb_subject.subject_name
     *
     * @mbggenerated
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_subject.subject_name
     *
     * @param subjectName the value for tb_subject.subject_name
     *
     * @mbggenerated
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_subject.create_time
     *
     * @return the value of tb_subject.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_subject.create_time
     *
     * @param createTime the value for tb_subject.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_subject.last_modify_time
     *
     * @return the value of tb_subject.last_modify_time
     *
     * @mbggenerated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_subject.last_modify_time
     *
     * @param lastModifyTime the value for tb_subject.last_modify_time
     *
     * @mbggenerated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_subject.remark
     *
     * @return the value of tb_subject.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_subject.remark
     *
     * @param remark the value for tb_subject.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}